(function (t) {
// es
t.add("slogan", "Constructor de mazos para TravellerCCG", "messages", "es");
t.add("data_load_fail", "No fue posible cargar los datos. Haga click <a href='javascript:window.location.reload(true)'>aqu\u00ed<\/a> para recargar la p\u00e1gina.", "messages", "es");
t.add("login_required", "Debes estar identificado para realizar esta operaci\u00f3n", "messages", "es");
t.add("userby", "por %user%", "messages", "es");
t.add("noimage", "Sin imagen", "messages", "es");
t.add("seemore.faction", "M\u00e1s de esta facci\u00f3n", "messages", "es");
t.add("nav.mydecks", "Mis mazos", "messages", "es");
t.add("nav.decklists", "Mazos", "messages", "es");
t.add("nav.cards", "Cartas", "messages", "es");
t.add("nav.reviews", "Rese\u00f1as", "messages", "es");
t.add("nav.rules", "Reglas", "messages", "es");
t.add("nav.rulesreference", "Gu\u00eda de referencia", "messages", "es");
t.add("nav.faq", "F.A.Q.", "messages", "es");
t.add("nav.tournamentregulations", "Normativa para torneos", "messages", "es");
t.add("nav.advancedsearch", "B\u00fasqueda avanzada", "messages", "es");
t.add("nav.cardsearch", "Buscar carta", "messages", "es");
t.add("nav.user.loginregister", "Identificarse o registrarse", "messages", "es");
t.add("nav.user.editaccount", "Editar cuenta", "messages", "es");
t.add("nav.user.profile", "Perfil p\u00fablico", "messages", "es");
t.add("nav.user.logout", "Salir", "messages", "es");
t.add("forms.save", "Guardar", "messages", "es");
t.add("forms.edit", "Editar", "messages", "es");
t.add("forms.publish", "Publicar", "messages", "es");
t.add("forms.delete", "Borrar", "messages", "es");
t.add("forms.cancel", "Cancelar", "messages", "es");
t.add("forms.add", "A\u00f1adir", "messages", "es");
t.add("forms.remove", "Eliminar", "messages", "es");
t.add("forms.import", "Importar", "messages", "es");
t.add("forms.upload", "Subir", "messages", "es");
t.add("forms.reset", "Limpiar", "messages", "es");
t.add("forms.copy", "Copiar", "messages", "es");
t.add("forms.clone", "Clonar", "messages", "es");
t.add("forms.close", "Cerrar", "messages", "es");
t.add("forms.print", "Imprimir", "messages", "es");
t.add("forms.download", "Descargar", "messages", "es");
t.add("forms.search", "Buscar", "messages", "es");
t.add("decks.privatedecks", "Mis mazos privados", "messages", "es");
t.add("decks.slotcount", "(%current%\/%max% mazos)", "messages", "es");
t.add("decks.version", "Versi\u00f3n %version%", "messages", "es");
t.add("decks.description", "Descripci\u00f3n", "messages", "es");
t.add("decks.defaultemptydesc", "*Sin descripci\u00f3n*", "messages", "es");
t.add("decks.problems.too_many_plots", "Contiene demasiadas Tramas", "messages", "es");
t.add("decks.problems.too_few_plots", "Contiene muy pocas Tramas", "messages", "es");
t.add("decks.problems.too_many_different_plots", "Contiene m\u00e1s de una Trama duplicada", "messages", "es");
t.add("decks.problems.too_many_agendas", "Contiene m\u00e1s de una Estrategia", "messages", "es");
t.add("decks.problems.too_few_cards", "Contiene muy pocas cartas", "messages", "es");
t.add("decks.problems.too_many_copies", "Contiene demasiadas copias de la misma carta (por t\u00edtulo)", "messages", "es");
t.add("decks.problems.invalid_cards", "Contiene cartas prohibidas (cartas no permitidas por la Facci\u00f3n o la Estrategia)", "messages", "es");
t.add("decks.problems.agenda", "No se ajusta a las condiciones de la Estrategia", "messages", "es");
t.add("decks.build.choose.faction", "Elige tu Facci\u00f3n", "messages", "es");
t.add("decks.build.choose.agenda", "Elige tu Estrategia", "messages", "es");
t.add("decks.build.choose.noagenda", "Sin Estrategia", "messages", "es");
t.add("decks.build.start", "Crear el mazo y empezar a construirlo", "messages", "es");
t.add("decks.build.newname.noagenda", "Nuevo mazo: %faction%", "messages", "es");
t.add("decks.build.newname.agenda", "Nuevo mazo: %faction%, %agenda%", "messages", "es");
t.add("decks.build.errors.nofaction", "Se requiere una Facci\u00f3n.", "messages", "es");
t.add("decks.edit.unsaved", "Este mazo tiene cambios sin guardar. Por favor, guarda el mazo o cancela los cambios antes de seguir modific\u00e1ndolo.", "messages", "es");
t.add("decks.edit.refresh", "Recargar los datos de la aplicaci\u00f3n", "messages", "es");
t.add("decks.edit.tabs.build", "Construir", "messages", "es");
t.add("decks.edit.tabs.notes", "Notas", "messages", "es");
t.add("decks.edit.tabs.test", "Pruebas", "messages", "es");
t.add("decks.edit.tabs.charts", "Gr\u00e1ficas", "messages", "es");
t.add("decks.edit.tabs.history", "Historia", "messages", "es");
t.add("decks.edit.build.help", "Ayuda de filtros", "messages", "es");
t.add("decks.edit.build.sets.label", "Cap\u00edtulos", "messages", "es");
t.add("decks.edit.build.sets.hint", "May\u00fas+Click para seleccionar solo uno; Alt+May\u00fas+Click para seleccionar todas las otras opciones", "messages", "es");
t.add("decks.edit.build.options.label", "Opciones", "messages", "es");
t.add("decks.edit.build.options.show.unusable", "Mostrar cartas que no se pueden usar", "messages", "es");
t.add("decks.edit.build.options.show.onlyused", "S\u00f3lo mostrar cartas usadas", "messages", "es");
t.add("decks.edit.build.options.display", "{1} Mostrar en 1 columna | ]1, Inf] Mostrar en %cols% columnas", "messages", "es");
t.add("decks.edit.build.options.usecore", "{1} Usar 1 Caja b\u00e1sica | ]1, Inf] Usar %core% Cajas b\u00e1sicas", "messages", "es");
t.add("decks.edit.build.options.factype.cumulative", "Facci\u00f3n\/Tipo acumulativo", "messages", "es");
t.add("decks.edit.build.options.factype.exclusive", "Facci\u00f3n\/Tipo exclusivo", "messages", "es");
t.add("decks.edit.build.searchhint", "Encuentra una carta o filtra la lista", "messages", "es");
t.add("decks.edit.notes.tags.label", "Etiquetas", "messages", "es");
t.add("decks.edit.notes.tags.hint", "Las etiquetas son \u00fatiles para filtrar tu lista de mazos, p. ej., <i>competitivo<\/i> o <i>justa<\/i>.", "messages", "es");
t.add("decks.edit.notes.notes.label", "Notas", "messages", "es");
t.add("decks.edit.notes.notes.hint", "Escribe # para introducir el nombre de una carta. Escribe $ para introducir un s\u00edmbolo.", "messages", "es");
t.add("decks.edit.form.name", "Nombre", "messages", "es");
t.add("decks.edit.form.cancel", "Cancelar cambios", "messages", "es");
t.add("decks.edit.meta.drawdeck", "{0} Mazo de robo: %count% cartas | {1} Mazo de robo: %count% carta | ]1,Inf] Mazo de robo: %count% cartas", "messages", "es");
t.add("decks.edit.meta.plotdeck", "{0} Mazo de tramas: %count% cartas | {1} Mazo de tramas: %count% carta | ]1,Inf] Mazo de tramas: %count% cartas", "messages", "es");
t.add("decks.edit.meta.packs", "Cap\u00edtulos: %packs%", "messages", "es");
t.add("decks.form.build", "Construir nuevo mazo", "messages", "es");
t.add("decks.form.uploadarchive", "Subir archivo", "messages", "es");
t.add("decks.form.new", "Nuevo mazo", "messages", "es");
t.add("decks.form.import.label", "Importar mazo", "messages", "es");
t.add("decks.form.import.copypaste", "Copiar\/pegar", "messages", "es");
t.add("decks.form.import.file", "Fichero", "messages", "es");
t.add("decks.form.selection.label", "Con los seleccionados", "messages", "es");
t.add("decks.form.selection.compare.label", "Comparar", "messages", "es");
t.add("decks.form.selection.compare.twodecks", "Comparar dos mazos", "messages", "es");
t.add("decks.form.selection.tags.label", "Etiquetas", "messages", "es");
t.add("decks.form.selection.tags.add", "A\u00f1adir una o m\u00e1s etiquetas", "messages", "es");
t.add("decks.form.selection.tags.remove", "Eliminar una o m\u00e1s etiquetas", "messages", "es");
t.add("decks.form.selection.tags.clear", "Quitar todas las etiquetas", "messages", "es");
t.add("decks.form.selection.delete.label", "Borrar", "messages", "es");
t.add("decks.form.selection.delete.selected", "Borrar todos los mazos seleccionados", "messages", "es");
t.add("decks.form.labelswitch", "Click para cambiar a esta etiqueta. May\u00fas+Click para alternar esta etiqueta.", "messages", "es");
t.add("decks.form.download.text", "Fichero de texto", "messages", "es");
t.add("decks.form.download.octgn", "Fichero OCTGN", "messages", "es");
t.add("decks.modals.card.go", "Ir a la p\u00e1gina de la carta", "messages", "es");
t.add("decks.modals.fileimport.title", "Subir fichero de mazo", "messages", "es");
t.add("decks.modals.fileimport.file.label", "Fichero", "messages", "es");
t.add("decks.modals.fileimport.type.label", "Tipo de fichero", "messages", "es");
t.add("decks.modals.fileimport.type.options.auto", "Autom\u00e1tico", "messages", "es");
t.add("decks.modals.fileimport.type.options.octgn", "OCTGN", "messages", "es");
t.add("decks.modals.fileimport.type.options.text", "Texto", "messages", "es");
t.add("decks.modals.delete.title", "Borrar mazo", "messages", "es");
t.add("decks.modals.delete.question", "\u00bfEst\u00e1s seguro de que deseas borrar el mazo %name%?", "messages", "es");
t.add("decks.modals.delete.confirm", "S\u00ed, b\u00f3rralo", "messages", "es");
t.add("decks.modals.deletelist.title", "Borrar mazos", "messages", "es");
t.add("decks.modals.deletelist.question", "\u00bfEst\u00e1s seguro de que deseas borrar todos los mazos seleccionados?", "messages", "es");
t.add("decks.modals.deletelist.confirm", "S\u00ed, b\u00f3rralos", "messages", "es");
t.add("decks.modals.tags.label", "Por favor, introduzca la lista de etiquetas, separadas por espacios", "messages", "es");
t.add("decks.modals.tags.hint", "una-etiqueta otra", "messages", "es");
t.add("decks.modals.tags.clear.question", "\u00bfEst\u00e1s seguro de que deseas quitar todas las etiquetas de los mazos seleccionados?", "messages", "es");
t.add("decks.modals.tags.clear.confirm", "S\u00ed, qu\u00edtalas", "messages", "es");
t.add("decks.published.title", "Versiones publicadas", "messages", "es");
t.add("decks.published.none", "Ninguna", "messages", "es");
t.add("decks.simulator.title", "Simulador de robo", "messages", "es");
t.add("decks.simulator.hint", "Click para robar; May\u00fas-click para robar desde el principio", "messages", "es");
t.add("decks.simulator.draw", "Robar", "messages", "es");
t.add("decks.simulator.all", "todo", "messages", "es");
t.add("decks.simulator.oddhint", "Probabilidades de robar al menos una copia de las cartas deseadas, despu\u00e9s de robar tantas del mazo, dependiendo del n\u00famero de copias incluidas (1 - 2 - 3)", "messages", "es");
t.add("decks.simulator.odds", "Probabilidades", "messages", "es");
t.add("decks.simulator.more", "m\u00e1s", "messages", "es");
t.add("decks.smartfilter.title", "Sintaxis del filtro inteligente", "messages", "es");
t.add("decks.smartfilter.example", "Ejemplo: <tt>m:1 s>3<\/tt> muestra todos los Personajes con icono <span class='icon-military'><\/span> y FUE mayor que 3", "messages", "es");
t.add("decks.smartfilter.filters.flavor", "Texto de ambientaci\u00f3n", "messages", "es");
t.add("decks.smartfilter.filters.claim", "Valor de conquista", "messages", "es");
t.add("decks.smartfilter.filters.pack_code", "Cap\u00edtulo", "messages", "es");
t.add("decks.smartfilter.filters.faction_code", "Facci\u00f3n", "messages", "es");
t.add("decks.smartfilter.filters.is_intrigue", "Icono de intriga", "messages", "es");
t.add("decks.smartfilter.filters.reserve", "Valor de reserva", "messages", "es");
t.add("decks.smartfilter.filters.illustrator", "Ilustrador", "messages", "es");
t.add("decks.smartfilter.filters.traits", "Rasgos", "messages", "es");
t.add("decks.smartfilter.filters.is_loyal", "Lealtad", "messages", "es");
t.add("decks.smartfilter.filters.is_military", "Icono militar", "messages", "es");
t.add("decks.smartfilter.filters.income", "Valor de ingresos", "messages", "es");
t.add("decks.smartfilter.filters.cost", "Coste", "messages", "es");
t.add("decks.smartfilter.filters.is_power", "Icono de poder", "messages", "es");
t.add("decks.smartfilter.filters.strength", "Fuerza", "messages", "es");
t.add("decks.smartfilter.filters.type_code", "Tipo", "messages", "es");
t.add("decks.smartfilter.filters.is_unique", "\u00danico", "messages", "es");
t.add("decks.smartfilter.filters.initiative", "Valor de iniciativa", "messages", "es");
t.add("decks.smartfilter.filters.text", "Texto", "messages", "es");
t.add("decks.smartfilter.filters.quantity", "Cantidad en el cap\u00edtulo", "messages", "es");
t.add("decks.charts.faction.title", "Cartas por Facci\u00f3n", "messages", "es");
t.add("decks.charts.faction.subtitle", "Solo mazo de robo", "messages", "es");
t.add("decks.charts.faction.label", "# cartas", "messages", "es");
t.add("decks.charts.icon.title", "Iconos de Personajes", "messages", "es");
t.add("decks.charts.icon.subtitle", "No se cuentan los duplicados", "messages", "es");
t.add("decks.charts.icon.tooltip.header", "Icono %type%", "messages", "es");
t.add("decks.charts.icon.tooltip.label", "# Personajes", "messages", "es");
t.add("decks.charts.strength.title", "Fuerza de Personajes", "messages", "es");
t.add("decks.charts.strength.subtitle", "No se cuentan los duplicados", "messages", "es");
t.add("decks.charts.strength.tooltip.header", "FUE %str%", "messages", "es");
t.add("decks.charts.strength.tooltip.label", "# Personajes", "messages", "es");
t.add("decks.charts.cost.title", "Coste de las cartas", "messages", "es");
t.add("decks.charts.cost.subtitle", "Se ignoran los costes X", "messages", "es");
t.add("decks.charts.cost.tooltip.header", "Coste %cost%", "messages", "es");
t.add("decks.charts.cost.tooltip.label", "# cartas", "messages", "es");
t.add("decks.history.timeremaining", "Tiempo restante", "messages", "es");
t.add("decks.history.columns.date", "Fecha", "messages", "es");
t.add("decks.history.columns.version", "Versi\u00f3n", "messages", "es");
t.add("decks.history.columns.changes", "Cambios", "messages", "es");
t.add("decks.history.columns.action", "Acci\u00f3n", "messages", "es");
t.add("decks.history.firstversion", "Primera versi\u00f3n", "messages", "es");
t.add("decks.history.unsaved", "sin guardar", "messages", "es");
t.add("decks.history.revert", "Deshacer", "messages", "es");
t.add("decks.compare.decknumber", "Mazo #%id%", "messages", "es");
t.add("decks.compare.plotdecks", "Mazos de trama", "messages", "es");
t.add("decks.compare.drawdecks", "Mazos de robo", "messages", "es");
t.add("decklist.publish.name", "Nombre", "messages", "es");
t.add("decklist.publish.placedhigh", "\u00bfConsigui\u00f3 una posici\u00f3n alta en un torneo?", "messages", "es");
t.add("decklist.publish.no", "No", "messages", "es");
t.add("decklist.publish.derived", "Derivado de (copia el id o la direcci\u00f3n del mazo del cual se ha inspirado \u00e9ste)", "messages", "es");
t.add("decklist.publish.description", "Descripci\u00f3n", "messages", "es");
t.add("decklist.publish.editor.hint", "Presiona # para insertar el nombre de una carta, $ para inserta un s\u00edmbolo del juego.", "messages", "es");
t.add("decklist.publish.editor.cardtolink", "Convertir el nombre de una carta en un enlace a \u00e9sta", "messages", "es");
t.add("decklist.publish.editor.entersymbol", "Insertar un s\u00edmbolo del juego", "messages", "es");
t.add("decklist.publish.editor.heading", "Cabecera %number%", "messages", "es");
t.add("decklist.publish.errors.unauthorized", "No tienes acceso a este mazo.", "messages", "es");
t.add("decklist.publish.errors.antispam.newbie", "Para prevenir el spam, las cuentas reci\u00e9n creadas deben esperar 24 horas antes de que puedan publicar un mazo.", "messages", "es");
t.add("decklist.publish.errors.antispam.limit", "Para prevenir el spam, las cuentas no pueden publicar durante 24 horas m\u00e1s mazos que su reputaci\u00f3n.", "messages", "es");
t.add("decklist.publish.errors.unreleased", "A\u00fan no puedes publicar este mazo porque tiene cartas que no han sido publicadas oficialmente.", "messages", "es");
t.add("decklist.publish.errors.invalid", "No se puede publicar este mazo porque es inv\u00e1lido.", "messages", "es");
t.add("decklist.publish.errors.pagetitle.spam", "Prevenci\u00f3n de spam", "messages", "es");
t.add("decklist.publish.warnings.published", "Este mazo <a href='%url%'>ya ha sido publicado<\/a> antes. Vas a crear un duplicado.", "messages", "es");
t.add("decklist.view.versions", "Versiones", "messages", "es");
t.add("decklist.view.published", "publicado", "messages", "es");
t.add("decklist.view.duplicate", "Duplicado de %duplicate%", "messages", "es");
t.add("decklist.view.comments.count", "{0} Sin comentarios | {1} %count% comentario | ]1,Inf] %count% comentarios", "messages", "es");
t.add("decklist.view.comments.hint", "Introduce tu comentario en formato Markdown. Escribe # para introducir el nombre de una carta. Escribe $ para introducir un s\u00edmbolo. Escribe @ para introducir el nombre de un usuario.", "messages", "es");
t.add("decklist.view.comments.submit", "Enviar comentario", "messages", "es");
t.add("decklist.view.social.like", "Me gusta", "messages", "es");
t.add("decklist.view.social.favorite", "Favorito", "messages", "es");
t.add("decklist.view.social.comment", "Comentario", "messages", "es");
t.add("decklist.view.social.version", "Versi\u00f3n", "messages", "es");
t.add("decklist.view.derived.title", "Derivado de", "messages", "es");
t.add("decklist.view.derived.none", "Ninguno. \u00c9ste es un mazo hecho de cero.", "messages", "es");
t.add("decklist.view.inspire.title", "Inspiraci\u00f3n para", "messages", "es");
t.add("decklist.view.inspire.none", "Ninguno todav\u00eda.", "messages", "es");
t.add("decklist.view.toolbar.edit", "Editar nombre y descripci\u00f3n del mazo", "messages", "es");
t.add("decklist.view.errors.notfound", "Mazo no encontrado.", "messages", "es");
t.add("decklist.list.types.popular", "Populares", "messages", "es");
t.add("decklist.list.types.recent", "Recientes", "messages", "es");
t.add("decklist.list.types.tournaments", "Torneos", "messages", "es");
t.add("decklist.list.types.hottopics", "Mazos de moda", "messages", "es");
t.add("decklist.list.types.hof", "Sal\u00f3n de la Fama", "messages", "es");
t.add("decklist.list.types.myfavorites", "Mis favoritos", "messages", "es");
t.add("decklist.list.types.mydecklists", "Mis mazos", "messages", "es");
t.add("decklist.list.titles.search", "B\u00fasqueda de mazos", "messages", "es");
t.add("decklist.list.titles.find", "Resultado de la b\u00fasqueda de mazos", "messages", "es");
t.add("decklist.list.titles.popular", "Mazos populares", "messages", "es");
t.add("decklist.list.titles.recent", "Mazos recientes", "messages", "es");
t.add("decklist.list.titles.tournament", "Torneos", "messages", "es");
t.add("decklist.list.titles.hottopics", "Mazos de moda", "messages", "es");
t.add("decklist.list.titles.halloffame", "Sal\u00f3n de la Fama", "messages", "es");
t.add("decklist.list.titles.favorites", "Mazos favoritos", "messages", "es");
t.add("decklist.list.titles.mine", "Mis mazos", "messages", "es");
t.add("decklist.list.search.faction.label", "Facci\u00f3n", "messages", "es");
t.add("decklist.list.search.faction.any", "cualquiera", "messages", "es");
t.add("decklist.list.search.author.label", "Nombre del autor", "messages", "es");
t.add("decklist.list.search.author.hint", "Introduce el nombre del autor", "messages", "es");
t.add("decklist.list.search.used.label", "Cartas usadas", "messages", "es");
t.add("decklist.list.search.used.hint", "Introduce nombre de carta", "messages", "es");
t.add("decklist.list.search.decklist.label", "Nombre del mazo", "messages", "es");
t.add("decklist.list.search.decklist.hint", "Introduce nombre del mazo", "messages", "es");
t.add("decklist.list.search.sort.label", "Ordenar", "messages", "es");
t.add("decklist.list.search.sort.popularity", "por Popularidad", "messages", "es");
t.add("decklist.list.search.sort.date", "por Fecha", "messages", "es");
t.add("decklist.list.search.sort.likes", "por N\u00famero de \\\"me gusta\\\"", "messages", "es");
t.add("decklist.list.search.sort.reputation", "por Reputaci\u00f3n del autor", "messages", "es");
t.add("decklist.list.search.allowed.label", "Cap\u00edtulos permitidos", "messages", "es");
t.add("decklist.list.search.allowed.onoff", "(%on% s\u00ed, %off% no)", "messages", "es");
t.add("decklist.list.search.allowed.core", "Caja b\u00e1sica \/ Deluxe", "messages", "es");
t.add("decklist.list.search.allowed.all", "todo", "messages", "es");
t.add("decklist.list.search.allowed.none", "ninguno", "messages", "es");
t.add("search.label", "Buscar", "messages", "es");
t.add("search.setbrowse", "Explorar cap\u00edtulos", "messages", "es");
t.add("search.title", "B\u00fasqueda de cartas", "messages", "es");
t.add("search.nametexts", "Nombre y textos", "messages", "es");
t.add("search.attributes", "Atributos", "messages", "es");
t.add("search.numerics", "Num\u00e9ricos", "messages", "es");
t.add("search.other", "Otros", "messages", "es");
t.add("search.previews", "Adelantos", "messages", "es");
t.add("search.submit", "B\u00fasqueda", "messages", "es");
t.add("search.any", "cualquiera", "messages", "es");
t.add("search.yes", "S\u00ed", "messages", "es");
t.add("search.no", "No", "messages", "es");
t.add("search.only", "S\u00f3lo", "messages", "es");
t.add("search.sort.name", "Ordenar por nombre", "messages", "es");
t.add("search.sort.set", "Ordenar por cap\u00edtulo", "messages", "es");
t.add("search.sort.faction", "Ordenar por facci\u00f3n", "messages", "es");
t.add("search.sort.type", "Ordenar por tipo", "messages", "es");
t.add("search.sort.cost", "Ordenar por coste", "messages", "es");
t.add("search.sort.expense", "Ordenar por gastos", "messages", "es");
t.add("search.view.list", "Ver como listado", "messages", "es");
t.add("search.view.spoiler", "Ver como spoilers", "messages", "es");
t.add("search.view.card", "Ver carta completa", "messages", "es");
t.add("search.view.scan", "Ver solo im\u00e1genes", "messages", "es");
t.add("search.view.short", "Ver como lista simple", "messages", "es");
t.add("pag.cardscount", "{0} No hay cartas | {1} Una carta | ]1,Inf] %count% cartas", "messages", "es");
t.add("card.traits.summer", "Verano", "messages", "es");
t.add("card.traits.winter", "Invierno", "messages", "es");
t.add("card.traits.scheme", "Conspiraci\u00f3n", "messages", "es");
t.add("card.traits.banner", "Estandarte", "messages", "es");
t.add("card.traits.maester", "Maestre", "messages", "es");
t.add("card.reviews.title", "Rese\u00f1as", "messages", "es");
t.add("card.reviews.none", "A\u00fan no hay rese\u00f1as para esta carta.", "messages", "es");
t.add("card.reviews.unreleased", "Las rese\u00f1as para esta carta se habilitar\u00e1n cuando \u00e9sta sea publicada oficialmente.", "messages", "es");
t.add("card.reviews.like", "Me gusta esta rese\u00f1a", "messages", "es");
t.add("card.reviews.edit", "Editar rese\u00f1a", "messages", "es");
t.add("card.reviews.write", "Escribir una rese\u00f1a", "messages", "es");
t.add("card.reviews.hint", "Escribe tu an\u00e1lisis de esta carta en al menos %min% caracteres. Puedes escribir tantas rese\u00f1as como tu reputaci\u00f3n. \u00c9ste no es lugar para preguntas o comentarios. Escribe # para introducir el nombre de una carta. Escribe $ para introducir un s\u00edmbolo.", "messages", "es");
t.add("card.reviews.submit", "Enviar rese\u00f1a", "messages", "es");
t.add("card.reviews.posted", "Tu rese\u00f1a ha sido enviada. Aparacer\u00e1 dentro de unos minutos.", "messages", "es");
t.add("card.reviews.comments.add", "A\u00f1adir un comentario", "messages", "es");
t.add("card.reviews.comments.hint", "Tu comentario", "messages", "es");
t.add("card.reviews.comments.post", "Enviar", "messages", "es");
t.add("card.reviews.comments.posted", "Tu comentario se ha enviado. Aparecer\u00e1 en unos pocos minutos.", "messages", "es");
t.add("card.reviews.alerts.minimum", "Tu rese\u00f1a debe tener al menos %min% caracteres.", "messages", "es");
t.add("card.info.name", "Nombre", "messages", "es");
t.add("card.info.unique", "\u00danico", "messages", "es");
t.add("card.info.complication", "Complicaci\u00f3n", "messages", "es");
t.add("card.info.text", "Texto", "messages", "es");
t.add("card.info.flavor", "Texto de ambientaci\u00f3n", "messages", "es");
t.add("card.info.faction", "Facci\u00f3n", "messages", "es");
t.add("card.info.set", "Cap\u00edtulo", "messages", "es");
t.add("card.info.cost", "Coste", "messages", "es");
t.add("card.info.costgold", "Coste\/Oro", "messages", "es");
t.add("card.info.type", "Tipo", "messages", "es");
t.add("card.info.strength", "Fuerza", "messages", "es");
t.add("card.info.str", "FUE", "messages", "es");
t.add("card.info.strini", "Fuerza\/Iniciativa", "messages", "es");
t.add("card.info.traits", "Rasgos", "messages", "es");
t.add("card.info.loyal", "Leal", "messages", "es");
t.add("card.info.nonloyal", "No Leal", "messages", "es");
t.add("card.info.income", "Ingresos", "messages", "es");
t.add("card.info.initiative", "Iniciativa", "messages", "es");
t.add("card.info.claim", "Conquista", "messages", "es");
t.add("card.info.reserve", "Reserva", "messages", "es");
t.add("card.info.plotlimit", "L\u00edmite por mazo", "messages", "es");
t.add("card.info.quantity", "Cantidad", "messages", "es");
t.add("card.info.illustrator", "Ilustrador", "messages", "es");
t.add("card.info.short.cost", "C.", "messages", "es");
t.add("card.info.short.expense", "Fu.", "messages", "es");
t.add("card.info.short.type", "T.", "messages", "es");
t.add("card.info.short.faction", "F.", "messages", "es");
t.add("challenges.military", "Militar", "messages", "es");
t.add("challenges.intrigue", "Intriga", "messages", "es");
t.add("challenges.power", "Poder", "messages", "es");
t.add("icon.baratheon", "Baratheon", "messages", "es");
t.add("icon.greyjoy", "Greyjoy", "messages", "es");
t.add("icon.intrigue", "Intriga", "messages", "es");
t.add("icon.lannister", "Lannister", "messages", "es");
t.add("icon.martell", "Martell", "messages", "es");
t.add("icon.military", "Militar", "messages", "es");
t.add("icon.thenightswatch", "Guardia de la Noche", "messages", "es");
t.add("icon.power", "Poder", "messages", "es");
t.add("icon.stark", "Stark", "messages", "es");
t.add("icon.targaryen", "Targaryen", "messages", "es");
t.add("icon.tyrell", "Tyrell", "messages", "es");
t.add("icon.unique", "\u00danico", "messages", "es");
t.add("icon.plot", "Trama", "messages", "es");
t.add("icon.attachment", "Accesorio", "messages", "es");
t.add("icon.location", "Lugar", "messages", "es");
t.add("icon.character", "Personaje", "messages", "es");
t.add("icon.event", "Evento", "messages", "es");
t.add("icon.agenda", "Estrategia", "messages", "es");
t.add("icon.neutral", "Neutral", "messages", "es");
t.add("keyword.renown.name", "Renombre", "messages", "es");
t.add("keyword.renown.title", "Despu\u00e9s de que ganes un reto en el que est\u00e9 participando este Personaje, puedes ganar 1 de Poder para este Personaje.", "messages", "es");
t.add("keyword.intimidate.name", "Intimidaci\u00f3n", "messages", "es");
t.add("keyword.intimidate.title", "Despu\u00e9s de que ganes un Reto en el que participe este Personaje como atacante, puedes elegir y arrodillar un Personaje controlado por el adversario derrotado cuya FUE sea igual o inferior a la diferencia de FUE por la que has ganado el reto.", "messages", "es");
t.add("keyword.stealth.name", "Sigilo", "messages", "es");
t.add("keyword.stealth.title", "Cuando este Personaje sea declarado como atacante, puedes elegir un Personaje sin Sigilo controlado por el jugador defensor. Ese Personaje no puede ser declaro defensor para este reto.", "messages", "es");
t.add("keyword.insight.name", "Perspicacia", "messages", "es");
t.add("keyword.insight.title", "Despu\u00e9s de que ganes un reto en el que est\u00e9 participando este Personaje, puedes robar 1 carta.", "messages", "es");
t.add("keyword.limited.name", "Limitada", "messages", "es");
t.add("keyword.limited.title", "Un jugador no puede reclutar ni jugar m\u00e1s de 1 carta Limitada en cada ronda, ni tampoco colocar m\u00e1s de 1 carta Limitada durante los preparativos de la partida.", "messages", "es");
t.add("keyword.pillage.name", "Pillaje", "messages", "es");
t.add("keyword.pillage.title", "Despu\u00e9s de que ganes un reto en el que est\u00e9 participando este Personaje, puedes descartar 1 carta de la parte superior del mazo del adversario derrotado.", "messages", "es");
t.add("keyword.terminal.name", "Terminal", "messages", "es");
t.add("keyword.terminal.title", "Si la carta vinculada abandona el juego, descarta este Accesorio.", "messages", "es");
t.add("keyword.ambush.name", "Emboscada", "messages", "es");
t.add("keyword.ambush.title", "Puedes pagar X de Oro para poner esta carta en juego desde tu mano durante la fase de Reto.", "messages", "es");
t.add("keyword.bestow.name", "Encomienda", "messages", "es");
t.add("keyword.bestow.title", "Cuando esta carta entre en juego, traslada hasta X de Oro de tu suministro de Oro hasta esta carta.", "messages", "es");
})(Translator);
